CREATE TABLE IF NOT EXISTS public.subjects (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code TEXT,
  name TEXT,
  grade_level INTEGER,
  units INTEGER,
  status TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  schedule TEXT
);

INSERT INTO public.subjects (id, code, name, grade_level, units, status, created_at, schedule)
VALUES
  (2, 'gymnast8', 'Gymnast', 7, 3, NULL, '2026-05-14 01:10:24.589925+00'::timestamptz, NULL),
  (3, '8Karatii', 'Karatii', 8, 3, NULL, '2026-05-18 11:58:25.257513+00'::timestamptz, NULL),
  (5, 'Bush11', 'Bushi', 11, 1, NULL, '2026-07-07 07:29:50.000926+00'::timestamptz, NULL),
  (6, 'mathe12', 'mathe', 12, 3, NULL, '2026-08-24 12:12:33.689377+00'::timestamptz, NULL),
  (7, 'grade10', 'grade10', 10, 3, NULL, '2026-09-04 02:16:42.235813+00'::timestamptz, NULL)
ON CONFLICT (id) DO NOTHING;
